apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-httpendpoint
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
  - name: server-endpoint
    targetPort: server-endpoint
    port: 8000
  type: NodePort
 
