apiVersion: v1
kind: Service
metadata:
  name: apacheservice03--1574245151
spec:
  ports:
  - name: http-endpoint
    port: 80
    protocol: TCP
    targetPort: http-endpoint
  selector:
    app: apachedeployment03--1762310980
  sessionAffinity: None
  type: NodePort
