apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  name: apachedeployment03--1762310980
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: apachedeployment03--1762310980
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: apachedeployment03--1762310980
    spec:
      containers:
      - image: httpd:latest
        imagePullPolicy: Always
        lifecycle:
          postStart:
            exec:
              command:
              - /bin/bash
              - -c
              - 'echo $(sed -n ''/^my_content: /s///p'' /tmp/cfg/input.properties)  >
                /usr/local/apache2/htdocs/index.html'
        name: apacheconfigmap03-1203889852
        ports:
        - containerPort: 80
          name: http-endpoint
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp/cfg
          name: apacheconfigmap03-1203889852-configmap-cfg-426563333
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: apacheconfigmap03-1203889852-configmap-cfg-426563333
        name: apacheconfigmap03-1203889852-configmap-cfg-426563333